CREATE TABLE PERSONAS
(
    ID_PERSONA INTEGER NOT NULL,
    NOMBRE VARCHAR2(70) NOT NULL,
    APELLIDO VARCHAR2(70) NOT NULL,
    EDAD INTEGER NOT NULL,
    SEXO VARCHAR2(1) NOT NULL,
    DOMICILIO VARCHAR2(100) NOT NULL,
    TELEFONO VARCHAR2(10) NOT NULL,
    
    CONSTRAINT PK_ID_PERSONA PRIMARY KEY (ID_PERSONA)
);


CREATE TABLE SOLICITUD
(
    ID_SOLICITUD INTEGER NOT NULL,
    ID_PERSONA INTEGER NOT NULL,
    CANTIDAD_MASC INTEGER NOT NULL,
    RAZONES_ADOP VARCHAR2(100),
    FECHA_SOL DATE NOT NULL,
    
    CONSTRAINT PK_ID_SOLICITUD PRIMARY KEY (ID_SOLICITUD),
    CONSTRAINT FK_ID_PERSONA FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA)
);


CREATE TABLE DONACIONES
(
    ID_DONACION INTEGER NOT NULL,
    ID_PERSONA INTEGER NOT NULL,
    DONACION INTEGER NOT NULL,
    DESCRIPCION_DON VARCHAR2(100),
    
    CONSTRAINT PK_ID_DONACION PRIMARY KEY (ID_DONACION),
    CONSTRAINT FK_ID_PERSONA_1 FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA)
);


CREATE TABLE RAZAS
(
    ID_RAZA INTEGER NOT NULL,
    NOMBRE VARCHAR2(70) NOT NULL,
  
    CONSTRAINT PK_ID_RAZA PRIMARY KEY (ID_RAZA)
);


CREATE TABLE MASCOTAS
(
    ID_MASCOTA INTEGER NOT NULL,
    ID_RAZA INTEGER NOT NULL,
    NOMBRE_MASC VARCHAR2(70) NOT NULL,
    AÑOS_MASC INTEGER NOT NULL,
    SEXO_MASC VARCHAR(1) NOT NULL,
    
    CONSTRAINT PK_ID_MASCOTA PRIMARY KEY (ID_MASCOTA), 
    CONSTRAINT FK_ID_RAZA FOREIGN KEY (ID_RAZA) REFERENCES RAZAS(ID_RAZA)
);


CREATE TABLE ADOPCIONES
(
    ID_ADOPCION INTEGER NOT NULL,
    ID_PERSONA INTEGER NOT NULL,
    ID_MASCOTA INTEGER NOT NULL,
    
    CONSTRAINT PK_ID_ADOPCION PRIMARY KEY (ID_ADOPCION),
    CONSTRAINT FK_ID_PERSONA_2 FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA),
    CONSTRAINT FK_ID_MASCOTA_2 FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS(ID_MASCOTA)
);


CREATE TABLE CONSULTAS
(
    ID_CONSULTA INTEGER NOT NULL,
    ID_MASCOTA INTEGER NOT NULL,
    MOTIVO VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(150),
    MONTO_PAGAR INTEGER NOT NULL,
    FECHA DATE NOT NULL,
    
    CONSTRAINT PK_ID_CONSULTA PRIMARY KEY (ID_CONSULTA),
    CONSTRAINT FK_MASCOTA FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS(ID_MASCOTA)
);


CREATE TABLE VACUNAS
(
    ID_VACUNA INTEGER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(100) NOT NULL,
    
    CONSTRAINT PK_ID_VACUNA PRIMARY KEY (ID_VACUNA)
);


CREATE TABLE MASC_VACUNA
(
    ID_MASCOTA INTEGER NOT NULL,
    ID_VACUNA INTEGER NOT NULL,
    FECHA_AP DATE NOT NULL,

    CONSTRAINT FK_ID_MASCOTA_1 FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS(ID_MASCOTA),
    CONSTRAINT FK_VACUNA FOREIGN KEY (ID_VACUNA) REFERENCES VACUNAS(ID_VACUNA)
);
